# Generated by Django 2.0.9 on 2018-11-13 09:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),        # https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#hstorefield
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(help_text='First name', max_length=50)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name (not common in Germany)', max_length=50, null=True)),
                ('last_name', models.CharField(help_text='Surname or family name', max_length=50)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.')], help_text='Choices: mr, ms', max_length=2, null=True)),
                ('contact_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('producer', 'Producer'), ('personnel', 'Personnel')], help_text='Choices: customer, supplier, producer, personnel', max_length=30, null=True)),
                ('customer_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('company', 'Company'), ('public', 'Public')], help_text='Choices: customer, company, public', max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                           List of 'address' objects with the structure:\n                           type (string - Choices: home, billing, business, delivery, mailing),\n                           street (string),\n                           house_number (string),\n                           postal_code: (string),\n                           city (string),\n                           country (string)\n                           ", null=True, size=None)),
                ('siteprofile_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of SiteProfile UUIDs', null=True, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                               List of 'email' objects with the structure:\n                               type (string - Choices: office, private, other),\n                               email (string)\n                               ", null=True, size=None)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                               List of 'phone' objects with the structure:\n                               type (string - Choices: office, mobile, home, fax),\n                               number (string)\n                               ", null=True, size=None)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Organization UUID')),
                ('workflowlevel1_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), help_text='List of Workflowlevel1 UUIDs', size=None)),
                ('workflowlevel2_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, help_text='List of Workflowlevel2 UUIDs', null=True, size=None)),
            ],
        ),
    ]
