# Generated by Django 2.0.9 on 2018-12-10 13:45

import contact.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                           List of 'address' objects with the structure:\n                           type (string - Choices: home, billing, business, delivery, mailing),\n                           street (string),\n                           house_number (string),\n                           postal_code: (string),\n                           city (string),\n                           country (string)\n                           ", null=True, size=None, validators=[contact.validators.validate_addresses]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                               List of 'email' objects with the structure:\n                               type (string - Choices: office, private, other),\n                               email (string)\n                               ", null=True, size=None, validators=[contact.validators.validate_emails]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="\n                               List of 'phone' objects with the structure:\n                               type (string - Choices: office, mobile, home, fax),\n                               number (string)\n                               ", null=True, size=None, validators=[contact.validators.validate_phones]),
        ),
    ]
