# Generated by Django 2.0.9 on 2019-02-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20181210_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_uuid',
            new_name='core_user_uuid',
        ),
    ]
