# Generated by Django 2.0.9 on 2019-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190227_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr.'), ('frau', 'Frau'), ('herr', 'Herr'), ('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('prof', 'Prof.'), ('prof dr', 'Prof. Dr.'), ('dr prof', 'Dr. Prof.')], help_text='Choices: dr, frau, herr, mr, ms, mrs, miss, prof, prof dr, dr prof', max_length=16, null=True),
        ),
    ]
