# Generated by Django 2.0.9 on 2019-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190301_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('prof dr', 'Prof. Dr.'), ('dr prof', 'Dr. Prof.'), ('prof', 'Prof.'), ('frau dr', 'Frau Dr.'), ('herr dr', 'Herr Dr.'), ('dr', 'Dr.'), ('frau', 'Frau'), ('herr', 'Herr'), ('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('miss', 'Miss')], help_text='Choices: prof dr, dr prof, prof, frau dr, herr dr, dr, frau, herr, mr, ms, mrs, miss', max_length=16, null=True),
        ),
    ]
