# Generated by Django 2.0.9 on 2019-03-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20190318_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='suffix',
            field=models.CharField(blank=True, help_text='Suffix for titles like dr., prof., dr. med. etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('family', 'Family')], help_text='Choices: mr, ms, mrs, miss, family', max_length=16, null=True),
        ),
    ]
