# Generated by Django 2.0.9 on 2019-03-29 14:34

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_move_titles_to_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, help_text='First name', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Organization UUID'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['workflowlevel1_uuids'], name='contact_con_workflo_064741_gin'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['workflowlevel2_uuids'], name='contact_con_workflo_3f40cd_gin'),
        ),
    ]
