# Generated by Django 2.0.13 on 2019-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20190329_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_id',
            field=models.CharField(blank=True, help_text='ID set by the customer. Must be unique in organization.', max_length=32, null=True),
        ),
    ]
