# Generated by Django 2.2.1 on 2019-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_contact_create_edit_dates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, customer_id=None), fields=('organization_uuid', 'customer_id'), name='unique_organization_customer_id'),
        ),
    ]
