# Generated by Django 2.2.1 on 2019-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_unique_customer_ids_w_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('contact', 'Contact'), ('company', 'Company'), ('public', 'Public')], help_text='Choices: customer, contact, company, public', max_length=30, null=True),
        ),
    ]
