# Generated by Django 2.2.1 on 2019-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_migrate_contact_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_organization_customer_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_id',
            field=models.IntegerField(blank=True, help_text='ID set by the customer. Must be unique in organization.', null=True),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, customer_id=None),
                                               fields=('organization_uuid', 'customer_id'),
                                               name='unique_organization_customer_id'),
        ),
    ]
