# Generated by Django 2.0.9 on 2018-11-23 10:10

import django.contrib.postgres.fields
from django.db import migrations, models

import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('owner', models.UUIDField()),
                ('name', models.CharField(help_text='Name', max_length=50)),
                ('start_date', models.DateTimeField(help_text='Start date')),
                ('end_date', models.DateTimeField(help_text='End date')),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('address', models.CharField(help_text='Address', max_length=100)),
                ('siteprofile_uuid', models.UUIDField(blank=True, help_text='Address where it takes place', null=True)),
                ('invitee_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of TolaUser UUIDs invited to the appointment.', null=True, size=None)),
                ('organization_uuid', models.UUIDField(blank=True, null=True)),
                ('workflowlevel2_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of WorkflowLevel2s added to the appointment.', null=True, size=None)),
                ('notes', models.CharField(blank=True, help_text='Notes', max_length=500, null=True)),
                ('contact_uuid', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Email Subject', max_length=100, null=True)),
                ('message', models.TextField(blank=True, help_text='Email Message', null=True)),
                ('recipient', models.CharField(help_text='Email Recipient', max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Sent at', null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('org_phone', models.CharField(blank=True, help_text='Organization Phone Number', max_length=20, null=True)),
                ('org_name', models.CharField(blank=True, help_text='Organization Name', max_length=50, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
            ],
        ),
    ]
