# Generated by Django 2.0.9 on 2019-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_new_notes_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnote',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], default=1, help_text='Choices: 1, 2'),
        ),
    ]
