# Generated by Django 2.0.9 on 2019-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20190227_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnote',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'OOO Reason'), (4, 'OOO Note')], default=1, help_text='Choices: 1, 2, 3, 4'),
        ),
    ]
