# Generated by Django 2.0.9 on 2019-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20190315_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnote',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
