# Generated by Django 2.2.1 on 2019-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20190321_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='summary',
            field=models.TextField(blank=True, help_text='Summarize the work done at the appointment.'),
        ),
    ]
